<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title ?? 'Cargo Summary Report' }}</title>
    <style>
        @font-face {
            font-family: 'NotoSansMyanmar';
            src: url({{ storage_path('fonts/NotoSansMyanmar-Regular.ttf') }}) format('truetype');
            font-weight: normal;
            font-style: normal;
        }
        body {
            font-family: 'NotoSansMyanmar', Arial, sans-serif;
            font-size: 10px;
            direction: rtl;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
        }
        .header p {
            margin: 5px 0 0 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #000;
            padding: 5px;
            text-align: right;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .footer {
            margin-top: 20px;
            text-align: left;
            font-size: 9px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Cargo Summary Report</h1>
        <p>Generated on: {{ $date }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>From</th>
                <th>To</th>
                <th>Sender</th>
                <th>Sender Phone</th>
                <th>Receiver</th>
                <th>Receiver Phone</th>
                <th>Car Number</th>
                <th>Registered Date</th>
                <th>Pickup Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['reports'] as $index => $report)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $report->from_city }} - {{ $report->from_gate }}</td>
                    <td>{{ $report->to_city }} - {{ $report->to_gate }}</td>
                    <td>{{ $report->sender_name }}</td>
                    <td>{{ $report->sender_phone }}</td>
                    <td>{{ $report->receiver_name }}</td>
                    <td>{{ $report->receiver_phone }}</td>
                    <td>{{ $report->car_number }}</td>
                    <td>{{ \Carbon\Carbon::parse($report->registered_date)->format('d/m/Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($report->to_pick_date)->format('d/m/Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ config('app.name') }}</p>
        <p>Total Records: {{ count($data['reports']) }}</p>
    </div>
</body>
</html>
